---
# - hosts: all
#   become: true
#   become_method: sudo
#   become_user: root
#   roles:
#     - all 

- hosts: 1sgar01-03
  become: true
  become_method: sudo
  become_user: root
  roles:
    - 1sgar01-03
...


