---
- name: restart postgres
  service: name=postgresql state=restarted

- name: Restart redis
  service:
    name: redis
    state: restarted

- name: Restart apache2
  service:
    name: apache2
    state: restarted


...